version: '3.7'

services:
    node:
        image: node:fermium-alpine
        container_name: uptownpanda.finance
        restart: always
        ports:
            - 3000:3000
        env_file: .docker-compose.env
        volumes:
            - ./src:/app
        working_dir: /app
        command: npm run dev