version: '3.7'

services:
    node:
        image: node:fermium-alpine
        container_name: uptownpanda.finance
        restart: always
        ports:
            - 3000:3000
        environment:
            - NEXTJS_ENVIRONMENT=development
            - NEXT_PUBLIC_TOKEN_CONTRACT_ADDRESS=0xa797b7f37999Af35131ed47D7b23a4AF77885f11
            - NEXT_PUBLIC_PRESALE_CONTRACT_ADDRESS=0x767503d653dc825e15C5B70b975F29E688F1CDea
            - NEXT_PUBLIC_LIQUIDITY_LOCK_CONTRACT_ADDRESS=0x9C33c8BA961498Fa528407ef35DE9e47f0Bc52b9
            - NEXT_PUBLIC_UP_FARM_CONTRACT_ADDRESS=0xB11d6C7c3c129388628fEcf2E6d1d92A2c3F8e0D
            - NEXT_PUBLIC_UP_ETH_FARM_CONTRACT_ADDRESS=0x4018994f138bfb30fFfc075AbAB13B48FC917046
            - NEXT_PUBLIC_WETH_FARM_CONTRACT_ADDRESS=0x2989105558FCE0C4bdC1E35D65e7dEddf392Fe40
            - NEXT_PUBLIC_WBTC_FARM_CONTRACT_ADDRESS=0x4B66EADb82Ca7370b72c2f92237D537c15fd4DB1
        volumes:
            - ./src:/app
        working_dir: /app
        command: npm run dev